[systems]
ui_name = "SYSTEMS"
type = "category"

[systems.terminator]
job_name = "Install Terminator"
ui_name = "Terminator"
type = "job"
run_command = "sudo apt install -y terminator"
check_command = "which terminator"
expected_result = 0
enable = true