[systems]
name = "SYSTEMS"
type = "category"

[systems.terminator]
name = "Terminator"
type = "package"
package_name = "terminator"
install_cmd = "sudo apt install -y terminator"
check_command = "which terminator"
expected_result = 0
enable = true