[[job]]
job_name = 'Install gcc'
run_command = 'sudo apt install -y gcc'
check_command = 'which gcc'
expected_result = 0

[[job]]
job_name = 'Install g++'
run_command = 'sudo apt install -y g++'
check_command = 'which g++'
expected_result = 0

[[job]]
job_name = 'Install Cmake'
run_command = 'sudo apt install -y cmake'
check_command = 'which cmake'
expected_result = 0

[[job]]
job_name = 'Install Ninja'
run_command = 'sudo apt install -y ninja-build'
check_command = 'which ninja'
expected_result = 0

[[job]]
job_name = 'Install ncurses'
run_command = 'sudo apt install -y libncurses5-dev libncursesw5-dev'
check_command = 'dpkg -l | grep -E "libncurses5-dev|libncursesw5-dev"'
expected_result = 0